name = "conversation"
version = "2.0.2"
target = "javascript"

description = "Gleam bindings for the standard JavaScript Request and Response APIs"
licences = ["MIT"]
repository = { type = "github", user = "MystPi", repo = "conversation" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[javascript]
runtime = "deno"

[javascript.deno]
allow_all = true

[dependencies]
gleam_stdlib = ">= 0.32.0 and < 2.0.0"
gleam_http = ">= 3.5.0 and < 5.0.0"
gleam_javascript = ">= 0.7.0 and < 2.0.0"

[dev-dependencies]
